---
- name: ENABLE NECESSARY FEATURES
  cisco.nxos.nxos_feature:
    feature: "{{item.feature }}"
  with_items: "{{ features }}"

- name: ENABLE NV OVERLAY EVPN
  cisco.nxos.nxos_evpn_global:
    nv_overlay_evpn: true

- name: CONFIGURE BGP GENERAL
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: "{{ ASN }}"
      log_neighbor_changes: true
      neighbors: 
        - neighbor_address: "{{ item.neighbor }}"
          inherit:
            peer: VXLAN_LEAF
  with_items: "{{ bgp_neighbors }}"

- name: CONFIGURE BGP TEMPLATES
  cisco.nxos.nxos_bgp_templates:
    config:
      as_number: "{{ ASN }}"
      neighbor:
        - name: VXLAN_LEAF
          remote_as: "{{ ASN }}"
          update_source: "loopback0"
          address_family:
            - afi: ipv4
              safi: unicast
              send_community: "extended"
              route_reflector_client: true
              soft_reconfiguration_inbound:
                set: true
         
            - afi: l2vpn
              safi: evpn
              send_community: "extended"
              route_reflector_client: true



  