all:
  children:
    alpines:
      hosts:
        A1:
          ansible_host: 10.208.116.108
        A2:
          ansible_host: 10.208.116.107
        A3:
          ansible_host: 10.208.116.109
    switches:
      children:
        spines:
          hosts:
            S1:
              ansible_host: 10.208.116.103
            S2:
              ansible_host: 10.208.116.101
        leaves:
          hosts:
            L1:
              ansible_host: 10.208.116.102
            L2:
              ansible_host: 10.208.116.105
            L3:
              ansible_host: 10.208.116.104
