---
- name: ENABLE NECESSARY FEATURES
  cisco.nxos.nxos_feature:
    feature: "{{ item.feature }}"
  with_items: "{{ features }}"

- name: ENABLE NV OVERLAY EVPN
  cisco.nxos.nxos_evpn_global:
    nv_overlay_evpn: true

- name: NVE Interface
  cisco.nxos.nxos_vxlan_vtep:
    interface: nve1
    host_reachability: true
    source_interface: Loopback0
    shutdown: false

- name: VNIs under NVE
  cisco.nxos.nxos_vxlan_vtep_vni:
    interface: nve1
    vni: "{{ item.vni }}"
    suppress_arp: true
    multicast_group: "{{ item.group }}"
  with_items: "{{ vni }}"

- name: L3VNI
  cisco.nxos.nxos_vxlan_vtep_vni:
    interface: nve1
    vni: 10999
    assoc_vrf: true

- name: VLAN for L3VNI
  cisco.nxos.nxos_vlans:
    config:
      - vlan_id: 999
        enabled: true
        mapped_vni: 10999

- name: Set SVI for L3VPN
  cisco.nxos.nxos_config:
    lines:
      - no shutdown
      - vrf member L3VNI
      - ip forward
    parents: interface Vlan999

- name: ANYCAST-GATEWAY-MAC
  cisco.nxos.nxos_overlay_global:
    anycast_gateway_mac: aaaa.bbbb.0001

- name: CREATE L3VNI VRF
  cisco.nxos.nxos_vrf:
    name: L3VNI
    rd: auto
    vni: 10999

- name: AF FOR L3VPN VRF
  cisco.nxos.nxos_vrf_af:
    vrf: L3VNI
    afi: ipv4
    route_target_both_auto_evpn: true

- name: IP IGMP SNOOPING VXLAN
  cisco.nxos.nxos_config:
    lines: ip igmp snooping vxlan

- name: CONFIGURE BGP GENERAL
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: "{{ ASN }}"
      log_neighbor_changes: true
      vrfs:
        - vrf: L3VNI
          log_neighbor_changes: true
      neighbors: 
        - neighbor_address: "{{ item.neighbor }}"
          inherit:
            peer: VXLAN_SPINE
  with_items: "{{ bgp_neighbors }}"

- name: CONFIGURE BGP TEMPLATES
  cisco.nxos.nxos_bgp_templates:
    config:
      as_number: "{{ ASN }}"
      neighbor:
        - name: VXLAN_SPINE
          remote_as: "{{ ASN }}"
          update_source: "loopback0"
          address_family:
            - afi: ipv4
              safi: unicast
              send_community: "extended"
              soft_reconfiguration_inbound:
                set: true
            - afi: l2vpn
              safi: evpn
              send_community: "extended"

- name: BGP AF configuration
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: "{{ ASN }}"
      address_family:
        - afi: ipv4
          safi: unicast
        - afi: l2vpn
          safi: evpn

- name: EVPN VNI configuration
  cisco.nxos.nxos_evpn_vni:
    vni: "{{ item.vni }}"
    route_distinguisher: auto
    route_target_import: auto
    route_target_export: auto
  with_items: "{{ vni }}"
